version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - KEEPA_API_KEY=${KEEPA_API_KEY}
      - OPENROUTER_MODEL=${OPENROUTER_MODEL:-google/gemini-2.5-flash-lite}
      - BATCH_SIZE=${BATCH_SIZE:-30}
      - MAX_CONCURRENT_REQUESTS=${MAX_CONCURRENT_REQUESTS:-0}
      - FRONTEND_URL=${FRONTEND_URL:-*}
    restart: unless-stopped