version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - KEEPA_API_KEY=${KEEPA_API_KEY}
      - OPENROUTER_MODEL=${OPENROUTER_MODEL:-google/gemini-2.5-flash-lite}
      - BATCH_SIZE=${BATCH_SIZE:-30}
      - MAX_CONCURRENT_REQUESTS=${MAX_CONCURRENT_REQUESTS:-0}
      - FRONTEND_URL=${FRONTEND_URL:-*}
      - PORT=8000
    volumes:
      # For development only - remove in production
      - .:/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s